### ISSUE TITLE
[enhancement] Complete missing race 

### ISSUE THREAD

**Issue by Ilanss** [Ceezik/ponce-tournois-mario-kart#57]
It would be nice to be able at the end of the tournament to complete missing race with your average point. Like this we would be able to see a projection of our results if we had finished all the races without having to enter dummy race (thus modifying racetrack stats).
It could be as simple as a "close tournament" button to click that fill automatically what's missing.
Or at the very least letting people leave empty the "track" input to simulate this (would'nt be ideal).

**Comment by Ceezik** [comment]
It would be very nice if we could see our potential score if we made all races, however I'm not a big fan of the idea of completing missing races with the average point 🤔 
Maybe I can show the info `Score maximum réalisable` next to `Nombre de points` in the tournament infos, I wiil think about it. But I'm afraid it will spoil the result of the bet sometimes 😕
